<?php

declare (strict_types=1);
namespace Cawl\Vendor;

// phpcs:disable CAWL.CodeQuality.LineLength.TooLong
use Cawl\Vendor\Dhii\Services\Factory;
return new Factory([], static function () : array {
    return \array_merge(['enabled' => ['title' => \__('Enable/Disable', 'cawl-for-woocommerce'), 'type' => 'checkbox', 'label' => \__('Enable SEPA Direct Debit (CAWL)', 'cawl-for-woocommerce'), 'default' => 'no'], 'title' => ['title' => \__('Title', 'cawl-for-woocommerce'), 'type' => 'text', 'description' => \__('Personalize the payment method title on the checkout page.', 'cawl-for-woocommerce'), 'desc_tip' => \__('If left empty, the default payment method name will be displayed on the checkout page.', 'cawl-for-woocommerce'), 'placeholder' => \__('SEPA Direct Debit', 'cawl-for-woocommerce')], 'sdd_signature_type_warning' => ['type' => 'content', 'description' => '<div class="wlop-warning-field">' . \esc_html__('Please ensure the mandate signing method is configured correctly if you offer SEPA Direct Debit to your customers; otherwise, transactions may be refused.', 'cawl-for-woocommerce') . '</div>'], 'sdd_signature_type' => ['title' => \__('SDD signature type', 'cawl-for-woocommerce'), 'type' => 'select', 'default' => 'SMS', 'options' => ['SMS' => 'SMS', 'UNSIGNED' => 'UNSIGNED', 'TICK_BOX' => 'TICK_BOX', 'AIS' => 'AIS'], 'description' => \__('Define how you want the SEPA mandate to be signed. SMS will send a message to the phone number your customer has provided, and UNSIGNED will proceed with the payment without signature.', 'cawl-for-woocommerce'), 'desc_tip' => \true], 'sdd_signature_type_info' => ['type' => 'content', 'description' => \sprintf('<div style="max-width:800px;padding:10px 14px;background-color:#e5f5fa;border:1px solid #72aee6;border-left-width:4px;border-radius:4px;margin:8px 0;">' . '<p style="margin:0 0 8px;">%1$s</p>' . '<ul style="margin:0;padding-left:20px;list-style:disc;">%2$s%3$s%4$s</ul>' . '</div>', \esc_html__('Please note that not all signature types are available to every user. Depending on your partner, please choose as follows:', 'cawl-for-woocommerce'), '<li>' . \esc_html__('Worldline: SMS, UNSIGNED, or AIS', 'cawl-for-woocommerce') . '</li>', '<li>' . \esc_html__('PAYONE: UNSIGNED or TICK_BOX', 'cawl-for-woocommerce') . '</li>', '<li>' . \esc_html__('ANZ or CAWL: this setting does not apply', 'cawl-for-woocommerce') . '</li>')]]);
});
